services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: yonthen
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: